# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Plain Blog"
license = "MIT"
licenselink = "https://github.com/LiaungYip/plain-blog/blob/master/LICENSE"
description = ""
homepage = "https://github.com/LiaungYip/plain-blog/"
tags = ["blog", "minimal", "white"]
features = ["responsive", "google analytics"]
min_version = 0.18

[author]
  name = "Li-aung Yip"
  homepage = "https://www.penwatch.net/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
