name = "Plain Blog"
license = "MIT"
licenselink = "https://github.com/LiaungYip/plain-blog/blob/master/LICENSE"
description = "Hugo blog theme for speed demons."
homepage = "https://github.com/LiaungYip/plain-blog/"
demosite = "https://www.penwatch.net/"
tags = ["blog", "minimal", "white"]
features = ["responsive", "google analytics"]
min_version = 0.96

[author]
  name = "Li-aung Yip"
  homepage = "https://www.penwatch.net/"