languageCode = "en-us"
title = "plain-blog Demo"
baseURL = "http://example.org/"

themesDir = "../.."
theme = "plain-blog"

# copyright is shown in footer
# Example:
# copyright = "&copy; 2017-2022 Joe Bloggs"
copyright = "&copy; 2017-2022 Joe Bloggs"

# Probably not needed
# MetaDataFormat = "yaml"

# If your base url is not the site root, you must set canonifyURLs = "true"
# Example 1:
#   baseurl = "https://xyz.com/"
#   canonifyURLs = "false"
# Example 2:
#   baseurl = "https://xyz.com/spqr/"
#   canonifyURLs = "true"
canonifyURLs = "false"

[author]
	# Sets <meta name="author" ...> tag in <head>
    name = "Joe Bloggs"
	
    # Enable Google Analytics.
    # i.e.
    #
    # gaID = "UA-12345678-1"
    #
    # To find your tracking ID, see:
    # https://support.google.com/analytics/answer/1032385?hl=en
    gaID = ""

# Override the default taxonomies configuration.
# Default is to have two taxonomies - "categories" and "tags".
# We add "series" as a third taxonomy.
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			# If your website contains a lot of raw HTML (i.e. HTML tables)
			# then you may need to enable "unsafe" mode.
			# Read and understand https://github.com/gohugoio/hugo/issues/6581
			# before you touch this setting.
			# unsafe = true
	
	[markup.tableOfContents]
		endLevel = 3
		ordered = false
		startLevel = 1
	
	# The new default syntax highlighter is Chroma.
	# The "pygments" style is used because it goes well with a light-coloured
	# theme.
	# You may choose other styles - see:
	# https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages
	[markup.highlight]
		guessSyntax = true
		lineNos = true
		style = 'pygments'

[minify]
	minifyOutput = true


# Use file last modified date for lastmod
# See: https://www.ii.com/hugo-tips-fragments/#_frontmatter
[frontmatter]
	date = [ "publishDate", ":filename", "date", ":fileModTime" ]
	publishDate = [ "publishDate", ":filename", "date", ":fileModTime" ]
	lastmod = [ "lastmod", ":fileModTime" ]

# https://gohugo.io/content-management/related#configure-related-content
[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
# Tags normally gets added automatically, since we have added config
# for [related] we have to add this config explicitly.
#
# Refer the docs:
#
# > If you add a related config section, you need to add a complete 
# > configuration. It is not possible to just set, say, includeNewer
# > and use the rest from the Hugo defaults.
[[related.indices]]
  name = 'tags'
  weight = 80
# Categories does not normally get added, add it
[[related.indices]]
  name = 'categories'
  weight = 80

[params.footer]
	show_hugo = "true"
	show_last_modified_time = "false"

# Top menu
[[menu.top]]
    url = "/tags/"
    name = "Tags"
    weight = 1

[[menu.top]]
    url = "/categories/"
    name = "Categories"
    weight = 2

[[menu.top]]
    url = "/series/"
    name = "Series"
    weight = 3

[[menu.top]]
    url = "/about/"
    name = "About"
    weight = 4

[[menu.top]]
    url = "/contact/"
    name = "Contact"
    weight = 5

# Bottom menu entries
[[menu.bottom]]
	url = "/contact/"
	name = "Comments"
	weight = 1

[[menu.bottom]]
	url = "https://github.com/ExampleUser/"
	name = "GitHub"
	weight = 2

[[menu.bottom]]
	url = "https://twitter.com/ExampleUser"
	name = "Twitter"
	weight = 3

[[menu.bottom]]
	url = "https://www.facebook.com/ExampleUser"
	name = "Facebook"
	weight = 4

[[menu.bottom]]
	url = "https://github.com/LiaungYip/plain-blog/"
	name = "plain-blog theme for Hugo"
	weight = 5